plugins {
    id 'net.neoforged.moddev' version '2.0.141'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

neoForge {
    version = project.neoforge_version

    runs {
        client {
            client()
        }
        server {
            server()
        }
        clientData {
            clientData()
            programArguments.addAll '--mod', 'akw',
                '--all',
                '--output', file('src/main/generated').getAbsolutePath(),
                '--existing', file('src/main/resources').getAbsolutePath()
        }
        serverData {
            serverData()
            programArguments.addAll '--mod', 'akw',
                '--all',
                '--output', file('src/main/generated').getAbsolutePath(),
                '--existing', file('src/main/resources').getAbsolutePath()
        }
    }

    mods {
        akw {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources.srcDir 'src/main/generated'

processResources {
    inputs.property 'version', project.version
    filteringCharset 'UTF-8'
    filesMatching('META-INF/neoforge.mods.toml') {
        expand 'version': project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = 'UTF-8'
    it.options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from('LICENSE') {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}
